calcLines = [
    "That's some spell you're under. It won't be easy to break. And you can't even tell anyone else",
    "Wrong. I'm the fire demon, Calcifer!",
    "Easy. If you break the spell that chains me to this place, I'll break your spell in a flash",
    "Demons don't make promises.",
    "But I'm an exploited demon.",
    "I'm chained here by a contract with Howl, who works me to death.",
    "I'm the one who keeps this castle moving.",
    "If you figure out the secret contract, the spell will break. If you do that, I'll break your spell too.",
    "Granny. Granny! Boy, I've got my doubts about her.",
    "That's right, I won't cook for you",
    "Forget it, I'm a demon! I answer to no one!",
    "Hey! Hey! I never should've let this old lady in!",
    "Hey! Hey! I'll burn the bacon!",
    "She bullied me.",
    "[eating noises]",
    "You're all ganging up on me!",
    "Huh? Not that too!",
    "Sophie! Sophie, I'm going out!",
    "I'll die without some fresh wood!",
    "Wh-What are you doing?",
    "I'll fall, I'll fall! I'm in peril!",
    "Oh, no. Oh, no!",
    "I'm in danger!",
    "I'm in danger..! I'll go out.",
    "Oh, no. I'm slipping, I'm slipping!",
    "I'm in- I'll go- Sophie, hurry!",
    "If I die, Howl goes with me.",
    "What a lot of fuss. Of course I am!",
    "You think so? You really think so?!",
    "Stinks. You reek of burnt flesh and hot steel.",
    "Keep flying and one day you won't be able to change yourself back.",
    "Isn't it great! Sophie did this for me!",
    "I hate the fire in gunpowder. They have no manners.",
    "The Witch of the Waste",
    "They'll cry plenty later on, when they can't regain human form.",
    "Aren't you supposed to report to the king yourself?",
    "Oh no, not again.",
    "Yeah, wasting my hot water again.",
    "Stop, Howl! Cut it out!",
    "Cut it out, Howl! I'm going out!",
    "Sophie! Get over here!",
    "See you later!",
    "Oh no, you've gone to far...",
    "Sopihe, you'd better figure out how to break my spell quick. We're both running out of time.",
    "I can't tell you that. I'm a demon!",
    "That's comfidential information.",
    "How dare you! Howl will die with me!",
    "But Sophie, she's the Witch of the Waste!",
    "Why's she staring at me!",
    "Don't look at me, they blew in with Sophie!",
    "Be gentle...",
    "That granny fed me something nasty!",
    "Move? You're nuts! There's nothing there.",
    "Suliman will find us right away!",
    "I can't! My contract says I can't leave the fireplace.",
    "Watch it! Cut it out! Cut it out!",
    "If I leave, this house will collapse.",
    "I'd better go last. Even I don't know what will happen.",
    "I told you, it would collapse- Rain!",
    "The roof's leaking, I'll go out!",
    "It's wet here! [yells]",
    "Hurry! Too damp..!",
    "I told you, if we'd stayed put, How and I could've handled it.",
    "Eh? But there's no chimney here... And the wood's damp...",
    "I've heard that, but... You really think so?",
    "Then, give me something of yours, Sophie.",
    "I can't do it alone. How about your eyes?",
    "[grunting and lifting]",
    "Imagine what I could do with your eyes and your heart!",
    "Don't!",
    "Stop it!",
    "Cut it out!",
    "Sophie... I'm all worn out.",
    "Probably not. If you do it, Sophie. After all, we both survived the water you dumped on me.",
    "It's still only a child's heart.",
    "I'm alive! I'm free!",
    "I really missed you all. Besides, it looks like rain...",
    "[giggles]"
]